# Generated by Django 3.1.5 on 2023-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
