# Generated by Django 3.1.5 on 2023-11-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0002_auto_20231127_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetails',
            name='actual_delivery',
            field=models.DateField(),
        ),
    ]
