# Generated by Django 4.2.7 on 2023-11-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0003_auto_20231127_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
